### ISSUE TITLE
Meeting Notes 16/08/2024

### ISSUE THREAD

**Issue by anhzf** [anhzf/nextjs-cashier#1]
# Notes
- Kuantitas: kg,m,pcs
- Bisa bayar parsial
- List nama pengutang
- Notifikasi email
- Bisa edit jatoh tempo utang
- List transaksi pending
- List jumlah utang
- Search saat pilih produk berdasarkan nama/tag
- Print nota (thermal printer)
- Input tenggat waktu utang
- Prefer per tab untuk tampilan filtering
- yang dihitung sebagai pemasukan adalah transaksi status "completed"
- yang dihitung sebagai hutang adalah transaksi status "pending"
- Export csv bisa berdasarkan filter

# Stock Management (Feature request)
- Input stok melalui transaksi (In/Out transaction type)
- Statistik transaksi berdasarkan stok
- Reminder stok (top 10 stok tersedikit/item dengan stok <= 5)

# Todo
- [x] Product size unit field
  - [x] Product form
  - [x] View
- [x] Transaction partial payment
  - [x] Paid amount field
  - [x] List view
- [x] Transaction due date field
  - [x] Transaction form
- [x] Daily email notification to list debtor
- [x] Dashboard
  - [x] Debt amount total
  - [x] List transactions sorted by the due date (show the customer name, due date, and minus)
  - [x] Product list with stock <= 5
  - [x] Total income and outcome per week/period
- [x] Product search
  - [x] by Tag
  - [x] by Name
- [x] Print invoice (to thermal printer)
- [x] Export transaction with filter applied
- [x] Stock management
  - [x] Transaction for stocking
  - [x] Product list filter
  - [x] List view
  - [x] Add transaction constraints
