### ISSUE TITLE
Meeting Notes 02/09/2024

### ISSUE THREAD

**Issue by anhzf** [anhzf/nextjs-cashier#3]
# Notes
- List transaksi dan barang berdasarkan filter
- Tampilkan jumlah hutang
- Ganti label status lebih friendly
- Bug stok bisa minus
- Ubah format tanggal transaksi
- Tambah tombol "tambah produk" di halaman stok

# ToDo
- [x] List transaksi dan barang berdasarkan filter
- [x] Tampilkan jumlah hutang
- [x] Ganti label status lebih friendly
- [x] Bug stok bisa minus
- [x] Ubah format tanggal transaksi
- [x] Tambah tombol "tambah produk" di halaman stok
