### ISSUE TITLE
Meeting Notes 02/11/2024

### ISSUE THREAD

**Issue by anhzf** [anhzf/nextjs-cashier#4]
# Notes

## Bug
- Transaction list cannot scroll
- Product list cannot scroll
- Customer list cannot scroll

## Enhancement
- Selected transaction item should be on top (appear in view transaction)
- Transaction filter date can be selected by date only (not range)
- Add the amount of debt each customer for email notification
- CSV compatibility on Excel below 365
- The tag list is too long

# ToDo
- [x] Pagination/Infinite scroll for transaction list
- [x] Pagination/Infinite scroll for product list
- [x] Pagination/Infinite scroll for customer list
- [x] Workaround for product list in creating transaction (Implemented: Remove product list limit)
- [x] Support single date selection for transaction list
- [x] Fix selected transaction items layout
- [x] Change tag selection for product list to `<select>`
- [x] Add the amount of debt each customer for the email notification message
- [x] Fix or add a workaround for CSV Excel compatibility
